version: "3.2"

services:
  web:
    build: .
    ports:
      - 8080:8080
    networks:
      - app-tier
  cassandra:
    image: 'bitnami/cassandra:latest'
    networks:
      - app-tier
  
networks:
  app-tier:
    driver: bridge